### ISSUE TITLE
Needing of replace imp module for importlib in reason of new python 3.12+ 

### ISSUE THREAD

**Issue by atirage21** [olejar/Vgi2ShpConverter#3]
Nepodarilo sa načítať zásuvný modul 'Vgi2ShpConverter' z dôvodu chyby pri volaní metódy classFactory() 

ModuleNotFoundError: No module named 'imp' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/attila/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Vgi2ShpConverter/__init__.py", line 15, in classFactory
    from Vgi2ShpConverter.vgi2shpconverter import Vgi2ShpConverter
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/attila/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Vgi2ShpConverter/vgi2shpconverter.py", line 27, in 
    exec(get_vgi2shpconverter())
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/attila/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Vgi2ShpConverter/vgi2shpconverter.py", line 3, in get_vgi2shpconverter
    import imp, base64, marshal
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'imp'

Verzia Pythonu: 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0] 
Verzia QGISu: 3.34.4-Prizren Prizren, exported 

Cesta k Pythonu:
/usr/share/qgis/python
/home/attila/.local/share/QGIS/QGIS3/profiles/default/python
/home/attila/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python312.zip
/usr/lib/python3.12
/usr/lib/python3.12/lib-dynload
/usr/local/lib/python3.12/dist-packages
/usr/lib/python3/dist-packages
/home/attila/.local/share/QGIS/QGIS3/profiles/default/python

**Links for solution:**

https://discuss.python.org/t/how-do-i-migrate-from-imp/27885
https://github.com/python/cpython/issues/104212
https://stackoverflow.com/questions/61622881/transition-from-imp-to-importlib

**Comment by olejar** [comment]
Vratte sa na starsiu verziu QGIS, aplikacia "zatial" nepodporuje Python 3.12 zabudovany v najnovsej verzii QGIS ... Olejar

________________________________
Od: atirage21 ***@***.***>
Odoslané: nedeľa 6. októbra 2024 16:01
Komu: olejar/Vgi2ShpConverter ***@***.***>
Kópia: Subscribed ***@***.***>
Predmet: [olejar/Vgi2ShpConverter] Needing of replace imp module for importlib in reason of new python 3.12+ (Issue #3)


Nepodarilo sa načítať zásuvný modul 'Vgi2ShpConverter' z dôvodu chyby pri volaní metódy classFactory()

ModuleNotFoundError: No module named 'imp'
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
plugins[packageName] = package.classFactory(iface)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/attila/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Vgi2ShpConverter/init.py", line 15, in classFactory
from Vgi2ShpConverter.vgi2shpconverter import Vgi2ShpConverter
File "/usr/lib/python3/dist-packages/qgis/utils.py", line 892, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/attila/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Vgi2ShpConverter/vgi2shpconverter.py", line 27, in
exec(get_vgi2shpconverter())
^^^^^^^^^^^^^^^^^^^^^^
File "/home/attila/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Vgi2ShpConverter/vgi2shpconverter.py", line 3, in get_vgi2shpconverter
import imp, base64, marshal
File "/usr/lib/python3/dist-packages/qgis/utils.py", line 892, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'imp'

Verzia Pythonu: 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0]
Verzia QGISu: 3.34.4-Prizren Prizren, exported

Cesta k Pythonu:
/usr/share/qgis/python
/home/attila/.local/share/QGIS/QGIS3/profiles/default/python
/home/attila/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python312.zip
/usr/lib/python3.12
/usr/lib/python3.12/lib-dynload
/usr/local/lib/python3.12/dist-packages
/usr/lib/python3/dist-packages
/home/attila/.local/share/QGIS/QGIS3/profiles/default/python

Links for solution:

https://discuss.python.org/t/how-do-i-migrate-from-imp/27885
python/cpython#104212<https://github.com/python/cpython/issues/104212>
https://stackoverflow.com/questions/61622881/transition-from-imp-to-importlib
